apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: echoserver
