version: "3.8"

services:
  echoserver:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - LOGS__LEVEL=info
      - LOGS__FORMAT=default
      - ENABLE_LOGS=true
      - ENABLE_HOST=true
      - ENABLE_HTTP=true
      - ENABLE_REQUEST=true
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:80', timeout=2)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
