title: Echo Server
description: HTTP request/response service for testing and debugging
url: "https://bgarvit01.github.io"
baseurl: "/echoserver"
theme: minima

markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

