name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  docker:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    needs: test

  helm:
    uses: ./.github/workflows/helm-release.yml
    secrets: inherit
    permissions:
      contents: write
    needs: [test, docker]

  create-release:
    runs-on: ubuntu-latest
    needs: [test, docker, helm]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            - Docker image: `garvitbhateja/echoserver:${{ github.ref_name }}`
            - Helm chart: `helm repo add echo-server https://bgarvit01.github.io/echoserver && helm install my-echo-server echo-server/echo-server`
            - Documentation: https://bgarvit01.github.io/echoserver/
            
            ## Installation
            
            ### Docker
            ```bash
            docker run -p 80:80 garvitbhateja/echoserver:${{ github.ref_name }}
            ```
            
            ### Kubernetes
            ```bash
            kubectl apply -f https://raw.githubusercontent.com/bgarvit01/echoserver/${{ github.ref_name }}/k8s/echo-server-all.yaml
            ```
            
            ### Helm
            ```bash
            helm repo add echo-server https://bgarvit01.github.io/echoserver
            helm install my-echo-server echo-server/echo-server --version ${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
